# https://github.com/codespell-project/codespell#readme
# https://beta.ruff.rs
name: ruff
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install --user codespell[toml] ruff
    - run: codespell --quiet-level=3  # --ignore-words-list="" --skip="*.css,*.js,*.lock,*.po"
    - run: ruff --format=github --ignore=F523 --line-length=113 --target-version=py37 .
